# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

on:
  issue_comment:
    types: [created]
name: Automatically Trigger Azure Pipeline
jobs:
  trigger:
    name: TriggerAZP
    if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, '/ci-run')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build
        run: |
          echo "${AZP_TOKEN}" | az devops login --organization "https://dev.azure.com/hyperledger"
          runs=$(az pipelines build list --project "Fabric" | jq -c ".[] | select(.sourceVersion | contains(\"${SHA}\"))" | jq -r .status | grep -vc completed)
          if [[ $runs -eq 0 ]]; then
            az pipelines build queue --branch "refs/pull/${PR_NUMBER}/merge" --commit-id "${SHA}" --project "Fabric" --definition-name "Fabric-Pull-Request"
            curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST -d '{"body": "AZP build triggered!"}' "${COMMENT_URL}"
          else
            curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST -d '{"body": "AZP build already running!"}' "${COMMENT_URL}"
          fi
        env:
          AZP_TOKEN: ${{ secrets.AZP_TOKEN }}
          COMMENT_URL: ${{ github.event.issue.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
          SHA: ${{ github.sha }}
      - name: Report Failure
        if: ${{ failure() }}
        run: |
          curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST -d '{"body": "Failed to trigger build!"}' "${COMMENT_URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_URL: ${{ github.event.issue.comments_url }}
